INSERT INTO pg_catalog.pg_available_extensions (name, default_version, installed_version, comment) VALUES ('adminpack', '2.1', null, 'administrative functions for PostgreSQL');
INSERT INTO pg_catalog.pg_available_extensions (name, default_version, installed_version, comment) VALUES ('amcheck', '1.2', null, 'functions for verifying relation integrity');
INSERT INTO pg_catalog.pg_available_extensions (name, default_version, installed_version, comment) VALUES ('autoinc', '1.0', null, 'functions for autoincrementing fields');
INSERT INTO pg_catalog.pg_available_extensions (name, default_version, installed_version, comment) VALUES ('bloom', '1.0', null, 'bloom access method - signature file based index');
INSERT INTO pg_catalog.pg_available_extensions (name, default_version, installed_version, comment) VALUES ('bool_plperl', '1.0', null, 'transform between bool and plperl');
INSERT INTO pg_catalog.pg_available_extensions (name, default_version, installed_version, comment) VALUES ('bool_plperlu', '1.0', null, 'transform between bool and plperlu');
INSERT INTO pg_catalog.pg_available_extensions (name, default_version, installed_version, comment) VALUES ('btree_gin', '1.3', null, 'support for indexing common datatypes in GIN');
INSERT INTO pg_catalog.pg_available_extensions (name, default_version, installed_version, comment) VALUES ('btree_gist', '1.5', null, 'support for indexing common datatypes in GiST');
INSERT INTO pg_catalog.pg_available_extensions (name, default_version, installed_version, comment) VALUES ('citext', '1.6', null, 'data type for case-insensitive character strings');
INSERT INTO pg_catalog.pg_available_extensions (name, default_version, installed_version, comment) VALUES ('cube', '1.4', null, 'data type for multidimensional cubes');
INSERT INTO pg_catalog.pg_available_extensions (name, default_version, installed_version, comment) VALUES ('dblink', '1.2', null, 'connect to other PostgreSQL databases from within a database');
INSERT INTO pg_catalog.pg_available_extensions (name, default_version, installed_version, comment) VALUES ('dict_int', '1.0', null, 'text search dictionary template for integers');
INSERT INTO pg_catalog.pg_available_extensions (name, default_version, installed_version, comment) VALUES ('dict_xsyn', '1.0', null, 'text search dictionary template for extended synonym processing');
INSERT INTO pg_catalog.pg_available_extensions (name, default_version, installed_version, comment) VALUES ('dummy_index_am', '1.0', null, 'dummy_index_am - index access method template');
INSERT INTO pg_catalog.pg_available_extensions (name, default_version, installed_version, comment) VALUES ('earthdistance', '1.1', null, 'calculate great-circle distances on the surface of the Earth');
INSERT INTO pg_catalog.pg_available_extensions (name, default_version, installed_version, comment) VALUES ('file_fdw', '1.0', null, 'foreign-data wrapper for flat file access');
INSERT INTO pg_catalog.pg_available_extensions (name, default_version, installed_version, comment) VALUES ('fuzzystrmatch', '1.1', null, 'determine similarities and distance between strings');
INSERT INTO pg_catalog.pg_available_extensions (name, default_version, installed_version, comment) VALUES ('hstore', '1.7', null, 'data type for storing sets of (key, value) pairs');
INSERT INTO pg_catalog.pg_available_extensions (name, default_version, installed_version, comment) VALUES ('hstore_plperl', '1.0', null, 'transform between hstore and plperl');
INSERT INTO pg_catalog.pg_available_extensions (name, default_version, installed_version, comment) VALUES ('hstore_plperlu', '1.0', null, 'transform between hstore and plperlu');
INSERT INTO pg_catalog.pg_available_extensions (name, default_version, installed_version, comment) VALUES ('hstore_plpython2u', '1.0', null, 'transform between hstore and plpython2u');
INSERT INTO pg_catalog.pg_available_extensions (name, default_version, installed_version, comment) VALUES ('hstore_plpython3u', '1.0', null, 'transform between hstore and plpython3u');
INSERT INTO pg_catalog.pg_available_extensions (name, default_version, installed_version, comment) VALUES ('hstore_plpythonu', '1.0', null, 'transform between hstore and plpythonu');
INSERT INTO pg_catalog.pg_available_extensions (name, default_version, installed_version, comment) VALUES ('insert_username', '1.0', null, 'functions for tracking who changed a table');
INSERT INTO pg_catalog.pg_available_extensions (name, default_version, installed_version, comment) VALUES ('intagg', '1.1', null, 'integer aggregator and enumerator (obsolete)');
INSERT INTO pg_catalog.pg_available_extensions (name, default_version, installed_version, comment) VALUES ('intarray', '1.3', null, 'functions, operators, and index support for 1-D arrays of integers');
INSERT INTO pg_catalog.pg_available_extensions (name, default_version, installed_version, comment) VALUES ('isn', '1.2', null, 'data types for international product numbering standards');
INSERT INTO pg_catalog.pg_available_extensions (name, default_version, installed_version, comment) VALUES ('jsonb_plperl', '1.0', null, 'transform between jsonb and plperl');
INSERT INTO pg_catalog.pg_available_extensions (name, default_version, installed_version, comment) VALUES ('jsonb_plperlu', '1.0', null, 'transform between jsonb and plperlu');
INSERT INTO pg_catalog.pg_available_extensions (name, default_version, installed_version, comment) VALUES ('jsonb_plpython2u', '1.0', null, 'transform between jsonb and plpython2u');
INSERT INTO pg_catalog.pg_available_extensions (name, default_version, installed_version, comment) VALUES ('jsonb_plpython3u', '1.0', null, 'transform between jsonb and plpython3u');
INSERT INTO pg_catalog.pg_available_extensions (name, default_version, installed_version, comment) VALUES ('jsonb_plpythonu', '1.0', null, 'transform between jsonb and plpythonu');
INSERT INTO pg_catalog.pg_available_extensions (name, default_version, installed_version, comment) VALUES ('lo', '1.1', null, 'Large Object maintenance');
INSERT INTO pg_catalog.pg_available_extensions (name, default_version, installed_version, comment) VALUES ('ltree', '1.2', null, 'data type for hierarchical tree-like structures');
INSERT INTO pg_catalog.pg_available_extensions (name, default_version, installed_version, comment) VALUES ('ltree_plpython2u', '1.0', null, 'transform between ltree and plpython2u');
INSERT INTO pg_catalog.pg_available_extensions (name, default_version, installed_version, comment) VALUES ('ltree_plpython3u', '1.0', null, 'transform between ltree and plpython3u');
INSERT INTO pg_catalog.pg_available_extensions (name, default_version, installed_version, comment) VALUES ('ltree_plpythonu', '1.0', null, 'transform between ltree and plpythonu');
INSERT INTO pg_catalog.pg_available_extensions (name, default_version, installed_version, comment) VALUES ('moddatetime', '1.0', null, 'functions for tracking last modification time');
INSERT INTO pg_catalog.pg_available_extensions (name, default_version, installed_version, comment) VALUES ('pageinspect', '1.8', null, 'inspect the contents of database pages at a low level');
INSERT INTO pg_catalog.pg_available_extensions (name, default_version, installed_version, comment) VALUES ('pgcrypto', '1.3', null, 'cryptographic functions');
INSERT INTO pg_catalog.pg_available_extensions (name, default_version, installed_version, comment) VALUES ('pgrowlocks', '1.2', null, 'show row-level locking information');
INSERT INTO pg_catalog.pg_available_extensions (name, default_version, installed_version, comment) VALUES ('pgstattuple', '1.5', null, 'show tuple-level statistics');
INSERT INTO pg_catalog.pg_available_extensions (name, default_version, installed_version, comment) VALUES ('pg_buffercache', '1.3', null, 'examine the shared buffer cache');
INSERT INTO pg_catalog.pg_available_extensions (name, default_version, installed_version, comment) VALUES ('pg_freespacemap', '1.2', null, 'examine the free space map (FSM)');
INSERT INTO pg_catalog.pg_available_extensions (name, default_version, installed_version, comment) VALUES ('pg_prewarm', '1.2', null, 'prewarm relation data');
INSERT INTO pg_catalog.pg_available_extensions (name, default_version, installed_version, comment) VALUES ('pg_stat_statements', '1.8', null, 'track planning and execution statistics of all SQL statements executed');
INSERT INTO pg_catalog.pg_available_extensions (name, default_version, installed_version, comment) VALUES ('pg_trgm', '1.5', null, 'text similarity measurement and index searching based on trigrams');
INSERT INTO pg_catalog.pg_available_extensions (name, default_version, installed_version, comment) VALUES ('pg_visibility', '1.2', null, 'examine the visibility map (VM) and page-level visibility info');
INSERT INTO pg_catalog.pg_available_extensions (name, default_version, installed_version, comment) VALUES ('pldbgapi', '1.1', null, 'server-side support for debugging PL/pgSQL functions');
INSERT INTO pg_catalog.pg_available_extensions (name, default_version, installed_version, comment) VALUES ('plperl', '1.0', null, 'PL/Perl procedural language');
INSERT INTO pg_catalog.pg_available_extensions (name, default_version, installed_version, comment) VALUES ('plperlu', '1.0', null, 'PL/PerlU untrusted procedural language');
INSERT INTO pg_catalog.pg_available_extensions (name, default_version, installed_version, comment) VALUES ('plpgsql', '1.0', '1.0', 'PL/pgSQL procedural language');
INSERT INTO pg_catalog.pg_available_extensions (name, default_version, installed_version, comment) VALUES ('plpython2u', '1.0', null, 'PL/Python2U untrusted procedural language');
INSERT INTO pg_catalog.pg_available_extensions (name, default_version, installed_version, comment) VALUES ('plpython3u', '1.0', null, 'PL/Python3U untrusted procedural language');
INSERT INTO pg_catalog.pg_available_extensions (name, default_version, installed_version, comment) VALUES ('plpythonu', '1.0', null, 'PL/PythonU untrusted procedural language');
INSERT INTO pg_catalog.pg_available_extensions (name, default_version, installed_version, comment) VALUES ('pltcl', '1.0', null, 'PL/Tcl procedural language');
INSERT INTO pg_catalog.pg_available_extensions (name, default_version, installed_version, comment) VALUES ('pltclu', '1.0', null, 'PL/TclU untrusted procedural language');
INSERT INTO pg_catalog.pg_available_extensions (name, default_version, installed_version, comment) VALUES ('postgres_fdw', '1.0', null, 'foreign-data wrapper for remote PostgreSQL servers');
INSERT INTO pg_catalog.pg_available_extensions (name, default_version, installed_version, comment) VALUES ('refint', '1.0', null, 'functions for implementing referential integrity (obsolete)');
INSERT INTO pg_catalog.pg_available_extensions (name, default_version, installed_version, comment) VALUES ('seg', '1.3', null, 'data type for representing line segments or floating-point intervals');
INSERT INTO pg_catalog.pg_available_extensions (name, default_version, installed_version, comment) VALUES ('sslinfo', '1.2', null, 'information about SSL certificates');
INSERT INTO pg_catalog.pg_available_extensions (name, default_version, installed_version, comment) VALUES ('system_stats', '1.0', null, 'EnterpriseDB system statistics for PostgreSQL');
INSERT INTO pg_catalog.pg_available_extensions (name, default_version, installed_version, comment) VALUES ('tablefunc', '1.0', null, 'functions that manipulate whole tables, including crosstab');
INSERT INTO pg_catalog.pg_available_extensions (name, default_version, installed_version, comment) VALUES ('tcn', '1.0', null, 'Triggered change notifications');
INSERT INTO pg_catalog.pg_available_extensions (name, default_version, installed_version, comment) VALUES ('test_bloomfilter', '1.0', null, 'Test code for Bloom filter library');
INSERT INTO pg_catalog.pg_available_extensions (name, default_version, installed_version, comment) VALUES ('test_ext1', '1.0', null, 'Test extension 1');
INSERT INTO pg_catalog.pg_available_extensions (name, default_version, installed_version, comment) VALUES ('test_ext2', '1.0', null, 'Test extension 2');
INSERT INTO pg_catalog.pg_available_extensions (name, default_version, installed_version, comment) VALUES ('test_ext3', '1.0', null, 'Test extension 3');
INSERT INTO pg_catalog.pg_available_extensions (name, default_version, installed_version, comment) VALUES ('test_ext4', '1.0', null, 'Test extension 4');
INSERT INTO pg_catalog.pg_available_extensions (name, default_version, installed_version, comment) VALUES ('test_ext5', '1.0', null, 'Test extension 5');
INSERT INTO pg_catalog.pg_available_extensions (name, default_version, installed_version, comment) VALUES ('test_ext6', '1.0', null, 'test_ext6');
INSERT INTO pg_catalog.pg_available_extensions (name, default_version, installed_version, comment) VALUES ('test_ext7', '1.0', null, 'Test extension 7');
INSERT INTO pg_catalog.pg_available_extensions (name, default_version, installed_version, comment) VALUES ('test_ext8', '1.0', null, 'Test extension 8');
INSERT INTO pg_catalog.pg_available_extensions (name, default_version, installed_version, comment) VALUES ('test_ext_cyclic1', '1.0', null, 'Test extension cyclic 1');
INSERT INTO pg_catalog.pg_available_extensions (name, default_version, installed_version, comment) VALUES ('test_ext_cyclic2', '1.0', null, 'Test extension cyclic 2');
INSERT INTO pg_catalog.pg_available_extensions (name, default_version, installed_version, comment) VALUES ('test_ext_evttrig', '1.0', null, 'Test extension - event trigger');
INSERT INTO pg_catalog.pg_available_extensions (name, default_version, installed_version, comment) VALUES ('test_ginpostinglist', '1.0', null, 'Test code for ginpostinglist.c');
INSERT INTO pg_catalog.pg_available_extensions (name, default_version, installed_version, comment) VALUES ('test_integerset', '1.0', null, 'Test code for integerset');
INSERT INTO pg_catalog.pg_available_extensions (name, default_version, installed_version, comment) VALUES ('test_pg_dump', '1.0', null, 'Test pg_dump with an extension');
INSERT INTO pg_catalog.pg_available_extensions (name, default_version, installed_version, comment) VALUES ('test_predtest', '1.0', null, 'Test code for optimizer/util/predtest.c');
INSERT INTO pg_catalog.pg_available_extensions (name, default_version, installed_version, comment) VALUES ('test_rbtree', '1.0', null, 'Test code for red-black tree library');
INSERT INTO pg_catalog.pg_available_extensions (name, default_version, installed_version, comment) VALUES ('tsm_system_rows', '1.0', null, 'TABLESAMPLE method which accepts number of rows as a limit');
INSERT INTO pg_catalog.pg_available_extensions (name, default_version, installed_version, comment) VALUES ('tsm_system_time', '1.0', null, 'TABLESAMPLE method which accepts time in milliseconds as a limit');
INSERT INTO pg_catalog.pg_available_extensions (name, default_version, installed_version, comment) VALUES ('unaccent', '1.1', null, 'text search dictionary that removes accents');
INSERT INTO pg_catalog.pg_available_extensions (name, default_version, installed_version, comment) VALUES ('uuid-ossp', '1.1', null, 'generate universally unique identifiers (UUIDs)');
INSERT INTO pg_catalog.pg_available_extensions (name, default_version, installed_version, comment) VALUES ('xml2', '1.1', null, 'XPath querying and XSLT');