INSERT INTO pg_catalog.pg_config (name, setting) VALUES ('BINDIR', 'C:/POSTGR~1/13/bin');
INSERT INTO pg_catalog.pg_config (name, setting) VALUES ('DOCDIR', 'C:/POSTGR~1/13/doc');
INSERT INTO pg_catalog.pg_config (name, setting) VALUES ('HTMLDIR', 'C:/POSTGR~1/13/doc');
INSERT INTO pg_catalog.pg_config (name, setting) VALUES ('INCLUDEDIR', 'C:/POSTGR~1/13/include');
INSERT INTO pg_catalog.pg_config (name, setting) VALUES ('PKGINCLUDEDIR', 'C:/POSTGR~1/13/include');
INSERT INTO pg_catalog.pg_config (name, setting) VALUES ('INCLUDEDIR-SERVER', 'C:/POSTGR~1/13/include/server');
INSERT INTO pg_catalog.pg_config (name, setting) VALUES ('LIBDIR', 'C:/POSTGR~1/13/lib');
INSERT INTO pg_catalog.pg_config (name, setting) VALUES ('PKGLIBDIR', 'C:/POSTGR~1/13/lib');
INSERT INTO pg_catalog.pg_config (name, setting) VALUES ('LOCALEDIR', 'C:/POSTGR~1/13/share/locale');
INSERT INTO pg_catalog.pg_config (name, setting) VALUES ('MANDIR', 'C:/PostgreSQL/13/man');
INSERT INTO pg_catalog.pg_config (name, setting) VALUES ('SHAREDIR', 'C:/POSTGR~1/13/share');
INSERT INTO pg_catalog.pg_config (name, setting) VALUES ('SYSCONFDIR', 'C:/PostgreSQL/13/etc');
INSERT INTO pg_catalog.pg_config (name, setting) VALUES ('PGXS', 'C:/PostgreSQL/13/lib/pgxs/src/makefiles/pgxs.mk');
INSERT INTO pg_catalog.pg_config (name, setting) VALUES ('CONFIGURE', '--enable-thread-safety --enable-nls --with-ldap --with-openssl --with-uuid --with-libxml --with-libxslt --with-icu --with-tcl --with-perl --with-python');
INSERT INTO pg_catalog.pg_config (name, setting) VALUES ('CC', 'не записано');
INSERT INTO pg_catalog.pg_config (name, setting) VALUES ('CPPFLAGS', 'не записано');
INSERT INTO pg_catalog.pg_config (name, setting) VALUES ('CFLAGS', 'не записано');
INSERT INTO pg_catalog.pg_config (name, setting) VALUES ('CFLAGS_SL', 'не записано');
INSERT INTO pg_catalog.pg_config (name, setting) VALUES ('LDFLAGS', 'не записано');
INSERT INTO pg_catalog.pg_config (name, setting) VALUES ('LDFLAGS_EX', 'не записано');
INSERT INTO pg_catalog.pg_config (name, setting) VALUES ('LDFLAGS_SL', 'не записано');
INSERT INTO pg_catalog.pg_config (name, setting) VALUES ('LIBS', 'не записано');
INSERT INTO pg_catalog.pg_config (name, setting) VALUES ('VERSION', 'PostgreSQL 13.1');