INSERT INTO information_schema.sql_sizing (sizing_id, sizing_name, supported_value, comments) VALUES (97, 'MAXIMUM COLUMNS IN GROUP BY', 0, null);
INSERT INTO information_schema.sql_sizing (sizing_id, sizing_name, supported_value, comments) VALUES (99, 'MAXIMUM COLUMNS IN ORDER BY', 0, null);
INSERT INTO information_schema.sql_sizing (sizing_id, sizing_name, supported_value, comments) VALUES (100, 'MAXIMUM COLUMNS IN SELECT', 1664, null);
INSERT INTO information_schema.sql_sizing (sizing_id, sizing_name, supported_value, comments) VALUES (101, 'MAXIMUM COLUMNS IN TABLE', 1600, null);
INSERT INTO information_schema.sql_sizing (sizing_id, sizing_name, supported_value, comments) VALUES (1, 'MAXIMUM CONCURRENT ACTIVITIES', 0, null);
INSERT INTO information_schema.sql_sizing (sizing_id, sizing_name, supported_value, comments) VALUES (0, 'MAXIMUM DRIVER CONNECTIONS', null, null);
INSERT INTO information_schema.sql_sizing (sizing_id, sizing_name, supported_value, comments) VALUES (20000, 'MAXIMUM STATEMENT OCTETS', 0, null);
INSERT INTO information_schema.sql_sizing (sizing_id, sizing_name, supported_value, comments) VALUES (20001, 'MAXIMUM STATEMENT OCTETS DATA', 0, null);
INSERT INTO information_schema.sql_sizing (sizing_id, sizing_name, supported_value, comments) VALUES (20002, 'MAXIMUM STATEMENT OCTETS SCHEMA', 0, null);
INSERT INTO information_schema.sql_sizing (sizing_id, sizing_name, supported_value, comments) VALUES (106, 'MAXIMUM TABLES IN SELECT', 0, null);
INSERT INTO information_schema.sql_sizing (sizing_id, sizing_name, supported_value, comments) VALUES (25000, 'MAXIMUM CURRENT DEFAULT TRANSFORM GROUP LENGTH', null, null);
INSERT INTO information_schema.sql_sizing (sizing_id, sizing_name, supported_value, comments) VALUES (25001, 'MAXIMUM CURRENT TRANSFORM GROUP LENGTH', null, null);
INSERT INTO information_schema.sql_sizing (sizing_id, sizing_name, supported_value, comments) VALUES (25002, 'MAXIMUM CURRENT PATH LENGTH', 0, null);
INSERT INTO information_schema.sql_sizing (sizing_id, sizing_name, supported_value, comments) VALUES (25003, 'MAXIMUM CURRENT ROLE LENGTH', null, null);
INSERT INTO information_schema.sql_sizing (sizing_id, sizing_name, supported_value, comments) VALUES (34, 'MAXIMUM CATALOG NAME LENGTH', 63, 'Might be less, depending on character set.');
INSERT INTO information_schema.sql_sizing (sizing_id, sizing_name, supported_value, comments) VALUES (30, 'MAXIMUM COLUMN NAME LENGTH', 63, 'Might be less, depending on character set.');
INSERT INTO information_schema.sql_sizing (sizing_id, sizing_name, supported_value, comments) VALUES (31, 'MAXIMUM CURSOR NAME LENGTH', 63, 'Might be less, depending on character set.');
INSERT INTO information_schema.sql_sizing (sizing_id, sizing_name, supported_value, comments) VALUES (10005, 'MAXIMUM IDENTIFIER LENGTH', 63, 'Might be less, depending on character set.');
INSERT INTO information_schema.sql_sizing (sizing_id, sizing_name, supported_value, comments) VALUES (32, 'MAXIMUM SCHEMA NAME LENGTH', 63, 'Might be less, depending on character set.');
INSERT INTO information_schema.sql_sizing (sizing_id, sizing_name, supported_value, comments) VALUES (35, 'MAXIMUM TABLE NAME LENGTH', 63, 'Might be less, depending on character set.');
INSERT INTO information_schema.sql_sizing (sizing_id, sizing_name, supported_value, comments) VALUES (107, 'MAXIMUM USER NAME LENGTH', 63, 'Might be less, depending on character set.');
INSERT INTO information_schema.sql_sizing (sizing_id, sizing_name, supported_value, comments) VALUES (25004, 'MAXIMUM SESSION USER LENGTH', 63, 'Might be less, depending on character set.');
INSERT INTO information_schema.sql_sizing (sizing_id, sizing_name, supported_value, comments) VALUES (25005, 'MAXIMUM SYSTEM USER LENGTH', 63, 'Might be less, depending on character set.');